# TCL File Generated by Component Editor 15.1
# Wed Sep 21 13:44:33 PDT 2016
# DO NOT MODIFY


#
# clock_gen "Clock Generator" v1.0
#  2016.09.21.13:44:33
#
#

#
# request TCL package from ACDS 15.1
#
package require -exact qsys 15.1


#
# module clock_gen
#
set_module_property DESCRIPTION ""
set_module_property NAME clock_gen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Test Components"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Clock Generator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL clock_gen
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file test_components/clock_gen.vhd VHDL PATH clock_gen.vhd


#
# parameters
#
add_parameter CLK_MHZ INTEGER 1000
set_parameter_property CLK_MHZ DEFAULT_VALUE 1000
set_parameter_property CLK_MHZ DISPLAY_NAME CLK_MHZ
set_parameter_property CLK_MHZ TYPE INTEGER
set_parameter_property CLK_MHZ UNITS None
set_parameter_property CLK_MHZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_MHZ HDL_PARAMETER true


#
# display items
#


#
# connection point clock
#
add_interface clock clock start
set_interface_property clock associatedDirectClock ""
set_interface_property clock clockRate 0
set_interface_property clock clockRateKnown false
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk_out clk Output 1


#
# connection point clk_3x
#
add_interface clk_3x clock start
set_interface_property clk_3x associatedDirectClock ""
set_interface_property clk_3x clockRate 0
set_interface_property clk_3x clockRateKnown false
set_interface_property clk_3x ENABLED true
set_interface_property clk_3x EXPORT_OF ""
set_interface_property clk_3x PORT_NAME_MAP ""
set_interface_property clk_3x CMSIS_SVD_VARIABLES ""
set_interface_property clk_3x SVD_ADDRESS_GROUP ""

add_interface_port clk_3x clk_out_3x clk Output 1


#
# connection point clk_2x
#
add_interface clk_2x clock start
set_interface_property clk_2x associatedDirectClock ""
set_interface_property clk_2x clockRate 0
set_interface_property clk_2x clockRateKnown false
set_interface_property clk_2x ENABLED true
set_interface_property clk_2x EXPORT_OF ""
set_interface_property clk_2x PORT_NAME_MAP ""
set_interface_property clk_2x CMSIS_SVD_VARIABLES ""
set_interface_property clk_2x SVD_ADDRESS_GROUP ""

add_interface_port clk_2x clk_out_2x clk Output 1
